@EComm.API_HostAddress = http://localhost:5000

GET {{EComm.API_HostAddress}}/products

###

@id=1
GET {{EComm.API_HostAddress}}/products/{{id}}

###

POST {{EComm.API_HostAddress}}/products
Content-Type: application/json

{
  "productName":"xTesting"
}

###
