@EComm.API_HostAddress = http://localhost:5000

GET {{EComm.API_HostAddress}}/products?start=2
Authorization: Basic YWJjMTIz


###

GET {{EComm.API_HostAddress}}/products/search?q=M


###

@id=1
GET {{EComm.API_HostAddress}}/products/{{id}}

###

POST {{EComm.API_HostAddress}}/products
Content-Type: application/json

{
  "productName":"zMoretesting"
}

###
